config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end if Rails.env.production?

  mount Sidekiq::Web, at: "/sidekiq"

  get "/talks/:id/topics", to: redirect("/talks/%{id}")
  get "/talks", to: redirect("/talks/new")
  get "/talks/:id/current_visitor", to: "visitors#current_visitor", as: :current_visitor
  
  resources :talks do
      post :update_current_topic
    resources :topics, only: [:create, :index, :update, :edit, :destroy] do
      post :upvote
    end
    resources :visitors, only: [:new, :create] do
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "talks#index"
end

app/models/topic.rb
class Topic < ApplicationRecord
  self.implicit_order_column = "created_at"

  belongs_to :talk

  has_many :votes, dependent: :destroy

  validates :content, presence: { message: "Oops! Looks like you forgot to write a topic"}
  validates :content, length: { maximum: 1000, too_long: "Are you sure the other participants want to read a novel? Try shortening your topic a bit"}
  
  after_commit :broadcast_content, on: :update

  after_destroy :broadcast_content

  def broadcast_content
    talk.broadcast_content
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  include TalkScoped, ActionView::RecordIdentifier

  before_action :set_topic, only: [:update, :edit, :destroy]
  skip_before_action :verify_authenticity_token

  def create
    @topic = @talk.topics.new topic_params
    @topics = @talk.ordered_topics
    if @topic.save
      @talk.broadcast_content
    else
      respond_to do |format|
        format.html { render "talks/show", status: :unprocessable_entity }
      end
    end
  end 

  def edit
  end

  def upvote
    Topic.find(params[:topic_id]).votes.create!
  end

  def destroy
    if @topic.destroy
      render @talk
    else
      respond_to do |format|
        format.html { render "talks/show", status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to talk_url(@talk) }
      else
        format.html { }
      end
    end
  end

  private 
  def topic_params
    params.required(:topic).permit(:content)
  end

  def set_topic
    @topic = Topic.find(params[:id])
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topic_seperator(vector_ending, width, color)
    tag.svg(width: width, height: "16", viewBox: "0 0 #{width} 16", fill: "none" ) do 
      tag.path(class: "group-hover:stroke-white", d: "M2 13L12 3L22 13L32 3L42 13L52 3L62 13L72 #{vector_ending}", stroke: color, "stroke-width": "3")
    end
  end

  def seperator_types
    [["3L82 13L92 3L102 13L112 3", "114", "#A92F3E"], ["3L82 13", "84", "#375DA1"], ["3", "74", "#027540"]]
  end

  def number_of_lines(topic)
    (topic.size.to_f / 65.to_f).ceil
  end
end

app/views/topics/_index.html.erb
<span id="topics_count"><%= talk.topics.count %></span>

app/views/topics/_new.html.erb
<%= form_with model: [ talk, Topic.new ], data: { turbo: false }, html: { autocomplete: "off", class: "bg-white my-shadow-lg p-8 mt-2 mb-16 flex flex-col w-full" } do |form| %>
  <h2 class="bg-white italic text-6xl lg:text-2xl font-bold mb-6">Add topic</h2>
  <div class="flex flex-row gap-4">
   <%= form.text_area :content, size: "20x2", class: "p-2 w-5/6 #{@topic&.errors&.any? ? "border-2 border-red border-solid" : "border-2 border-black border-dashed" }" %>
    <%= render "shared/error_message", attribute: :content, object: @topic %>
   <%= form.submit "ADD", class: "my-shadow w-1/6 font-bold text-white bg-green transition duration-200 ease-in-out transform hover:bg-green-dark active:bg-green-darker text-center text-xl cursor-pointer" %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<% case talk.state %>
<% when 2 %>

  <%= turbo_frame_tag dom_id(topic, :edit) do %>
    <div class="hover:bg-rose-800 group flex flex-row justify-between">
      <div class="p-6 flex flex-col w-3/4">
        
        <div id="<%= dom_id(topic) %>" class="pb-6 group-hover:text-white">
          <%= topic.content %>
        </div>
        
        <div>
          <%= topic_seperator(*seperator_types.sample) %>
        </div>

      </div>
      <div class="group-hover:flex hidden flex-row items-center relative gap-2 text-white w-1/4 justify-end -right-60 pl-4">

          <%= link_to edit_talk_topic_path(talk, topic), class: "bg-rose-800 flex h-full w-full items-center justify-center my-shadow-lg", data: { turbo_frame: dom_id(topic, :edit) } do %>
          <p class="uppercase font-semibold">edit</p>
          <% end %>

          <%= button_to "delete", talk_topic_path(talk, topic), method: :delete, class: "font-semibold uppercase", form_class: "bg-rose-800 flex h-full w-full justify-center my-shadow-lg" %>
      </div>
    </div>
  <% end %>


<% when 3 %>

  <%= button_to talk_topic_upvote_path(talk, topic), data: { turbo: false }, id: dom_id(topic), method: :post, class: "w-full bg-white p-6 flex flex-row justify-between" do %>
    <p><%= topic.content %></p>
    <div class="flex flex-row items-center gap-4">
      <span class="material-icons-outlined text-3xl text-red"><%= topic.votes.size == 0 ? "star_outline" : "star" %></span>
      <p id="<%= dom_id(topic, :votes_count) %>"><%= topic.votes.size %></p>
    </div>
  <% end %>

<% when 4 %>

  <% if topic.current %>

    <div class="bg-green p-4">
      <div class="text-center bg-green text-white italic leading-loose font-semibold px-16 py-32 text-2xl border-8 border-double border-white">
        <%= topic.content %>
      </div>
    </div>

    <div class="flex flex-row gap-2 justify-between">
      <%= button_to talk_update_current_topic_path(talk), params: { direction: "back"}, data: { turbo: false, facilitator_target: "Facilitator" }, class: "hidden" do |form| %>
        <span class="material-icons">west</span>
      <% end %>
      <p>Topic <%= topic_counter + 1 %> of <%= topics.size %></p>
      <%= button_to talk_update_current_topic_path(talk), params: { direction: "next" }, data: { turbo: false, facilitator_target: "Facilitator" }, class: "hidden" do |form| %>
        <span class="material-icons">east</span>
      <% end %>
    </div>

  <% end %>

<% when 5 %>

<div id="<%= dom_id(topic) %>" class="w-full bg-white p-6 flex flex-row justify-between">
  <%= topic.content %>
   <span class="material-icons text-green"><%="check_circle" if topic.done?%></span>
</div>

<% end %>
 

app/views/topics/edit.html.erb
<%= turbo_frame_tag dom_id(@topic, :edit) do %>
  <div class="bg-rose-800 group flex flex-row justify-between">
    <div class="p-6 flex flex-col w-3/4">

    <%= form_with model: [ @talk, @topic], class:"", method: :patch, id: dom_id(@topic, :edit_topic_content_form) do |form| %>
      <%= form.text_area :content, class: "bg-white mb-6 w-full", rows: number_of_lines(@topic.content)  %>
    <% end %>

      <div>
        <%= topic_seperator("3L82 13L92 3L102 13L112 3", "114", "#FFF") %>
      </div>

    </div>
    <div class="flex flex-row items-center relative gap-2 text-white w-1/4 justify-end -right-60 pl-4">
        <%= button_tag type: "submit", form: dom_id(@topic, :edit_topic_content_form), class: "bg-rose-800 flex h-full w-full items-center justify-center my-shadow-lg" do %>
          <p class="uppercase font-semibold">update</p>
        <% end %>
        <%= button_to "delete", talk_topic_path(@talk, @topic), method: :delete, class: "font-semibold uppercase", form_class: "bg-rose-800 flex h-full w-full justify-center my-shadow-lg" %>
    </div>
  </div>

<% end %>