config/routes.rb
Rails.application.routes.draw do
  require "sidekiq/web"

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
  end if Rails.env.production?

  mount Sidekiq::Web, at: "/sidekiq"

  get "/talks/:id/topics", to: redirect("/talks/%{id}")
  get "/talks", to: redirect("/talks/new")
  get "/talks/:id/current_visitor", to: "visitors#current_visitor", as: :current_visitor
  
  resources :talks do
      post :update_current_topic
    resources :topics, only: [:create, :index, :update, :edit, :destroy] do
      post :upvote
    end
    resources :visitors, only: [:new, :create] do
    end
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "talks#index"
end

app/models/talk.rb
class Talk < ApplicationRecord
  self.implicit_order_column = "created_at"
  
  include Moderated

  has_many :topics, dependent: :destroy
  
  has_many :participations, dependent: :destroy
  has_many :visitors, -> { distinct }, through: :participations

  accepts_nested_attributes_for :visitors

  validates :theme, presence: { message: "Write an overall theme of the talk"}
  
  validates :duration, presence: { message: "How long time do you plan to spend?"}
  validates :duration, numericality: { only_integer: true, message: "How long time do you plan to spend in minutes?" }

  after_update_commit :broadcast_content
  
  after_update_commit :set_first_topic, if: :state_is_4_and_there_is_no_current_topic?

  def broadcast_content
    broadcast_replace_later_to "state_stream", target: ActionView::RecordIdentifier.dom_id(self), partial: "talks/partial_show", 
    locals: { talk: self, topics: self.ordered_topics.to_a, participants: self.visitors.online.only_participants.to_a } 
  end

  def broadcast_participants
    broadcast_replace_later_to "participants_stream", target: ActionView::RecordIdentifier.dom_id(self, :participants), partial: "talks/participants", 
    locals: { talk: self, participants: self.visitors.online.only_participants.to_a } 
  end

  def ordered_topics
    if state < 4
      topics.order(created_at: :desc)
    else
      topics_by_votes
    end
  end

  def topics_by_votes
    topics.left_joins(:votes).group("topics.id").order("count(topics.id) DESC")
  end

  def highest_voted_topic
    topics_by_votes[0]
  end

  def current_topic
    topics_by_votes.find_by(current:true)
  end

  def all_topics_are_done?
    !topics.where(done:false).any? && topics.size > 0
  end

  def facilitator
    participations.find_by(facilitator:true).visitor
  end

  private

  def state_is_4_and_there_is_no_current_topic?
    moderator.there_is_no_current_topic? && state == 4
  end

  def set_first_topic
    moderator.set_first_topic
  end
end

app/models/talk/moderated.rb
module Talk::Moderated
  def moderator
    @moderator ||= Talk::Moderator.new(self)
  end
end

app/models/talk/moderator.rb
class Talk::Moderator

  def initialize(talk)
    @talk = talk
  end

  def set_next_topic
    return finish_talk_state if next_topic.nil?
    
    switch_to(next_topic)
  end

  def set_previous_topic
    switch_to(previous_topic)
  end

  def set_first_topic
    talk.highest_voted_topic.update(current: true) unless there_are_no_topics
  end

  def there_is_no_current_topic?
    talk.current_topic == nil
  end

  private

  def there_are_no_topics
    talk.highest_voted_topic.nil?
  end

  def previous_topic
    talk.topics_by_votes[current_topic_index - 1]
  end

  def next_topic
    talk.topics_by_votes[current_topic_index + 1]
  end

  def current_topic_is_the_last?
    talk.topics_by_votes.to_a.size == current_topic_index + 1
  end

  def finish_talk_state
    talk.current_topic.update(current: false)
    talk.update(state: 5)
  end

  def current_topic_index
    talk.topics_by_votes.index(talk.current_topic)
  end

  def switch_to(topic)
    talk.current_topic.update(current: false)
    topic.update(current: true)
  end

  attr_reader :talk
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  include TalkScoped

  skip_before_action :verify_authenticity_token

  before_action :require_visitor_registrated!, only: :show
 
  # GET /talks/1 or /talks/1.json
  def show
    @topics = @talk.ordered_topics
    @topic = Topic.new
    @participants = @talk.visitors.online.only_participants
  end

  def index
  end

  def edit
    @visitor = Current.visitor
  end

  # GET /talks/new
  def new
    @talk = Talk.new
    @visitor = Current.visitor || @talk.visitors.build
  end

  def create
    @talk = Talk.new(talk_params)
    @visitor = Visitor.find_or_initialize_by(id: visitors_params[:visitors_attributes]["0"][:id], name: visitors_params[:visitors_attributes]["0"][:name] )
    respond_to do |format|
      if @talk.save && @visitor.valid?
        @talk.visitors << @visitor
        @participation = Participation.current(@talk, @visitor)
        @participation.update(facilitator:true)
        session[:visitor_id] = @visitor.id
        format.html { redirect_to talk_url(@talk), notice: "Wonderful. Let's get started!" }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @talk.update(talk_and_visitors_params)
        format.html { redirect_to talk_url(@talk) }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1 or /talks/1.json
  def destroy
    @talk.destroy

    respond_to do |format|
      format.html { redirect_to talks_url, notice: "Talk was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def update_current_topic
    case params[:direction]
      when "next"
        @talk.moderator.set_next_topic
      when "back"
        @talk.moderator.set_previous_topic
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def talk_params
      params.require(:talk).permit(:duration, :state, :theme)
    end
    
    def visitors_params
      params.require(:talk).permit(visitors_attributes: [:name, :id])
    end

    def talk_and_visitors_params
      params.require(:talk).permit(:duration, :state, :theme, visitors_attributes: [:name, :id])
    end
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/talks/_form.html.erb
<div class="flex-row flex bg-white my-shadow-lg mx-auto py-12 px-16 text-left mt-12"> 
<div class="flex flex-col w-full ">
  <p class="pb-8 text-4xl font-bold uppercase">Let's start with a bit of information!</p>
    <%= form_with model: talk, data: { turbo: false }, class: "flex flex-col gap-8" do |form| %>
    <div>
      <div class="flex flex-row justify-between items-baseline mb-2">
        <%= form.label "Theme", class: "italic text-2xl font-bold leading-none uppercase" %>
        <p class="opacity-50 text-black italic font-semibold">What is the overall theme of this talk?</p>
      </div>
      <%= form.text_field :theme, class: "#{talk&.errors&.include?(:theme) ? "border-2 border-red border-solid " : "border-solid border-2 border-black " }focus:outline-none h-12 italic font-bold px-4 w-full", autocomplete: "off" %>
      <%= render "shared/error_message", attribute: :theme, object: talk %>
    </div>
    <div>
      <div class="flex flex-row justify-between items-baseline mb-2">
        <%= form.label "Your name", class: "italic text-2xl font-bold leading-none uppercase" %>
        <p class="opacity-50 text-black italic font-semibold">Let the participants know who you are</p>
      </div>
      <%= form.fields_for :visitors, visitor do |visitor|%>
        <%= visitor.text_field :name, class: "#{visitor.object&.errors&.include?(:name) ? "border-2 border-red border-solid " : "border-solid border-2 border-black " } focus:outline-none h-12 italic font-bold px-4 w-full", autocomplete: "off" %>
        <%= render "shared/error_message", attribute: :name, object: visitor.object %>
      <% end %>
    </div>
    <div data-controller="duration">
      <div class="flex flex-row justify-between items-baseline mb-2">
        <%= form.label "Time available", class: "italic text-2xl font-bold leading-none uppercase" %>
        <p class="opacity-50 text-black italic font-semibold">How long do you have for the session?</p>
      </div>
      <%= form.select :duration, [ ["15 minutes", 15], ["30 minutes", 30], ["45 minutes", 45], ["60 minutes", 60], ["75 minutes", 75], ["90 minutes", 90] ], {:selected => 60}, data: { action: "duration#showDuration", duration_target: "getSelectedDuration" }, class: "#{talk&.errors&.include?(:duration) ? "border-2 border-red border-solid " : "border-solid border-2 border-black " } w-full focus:outline-none text-lg h-12 italic font-bold px-4" %>
      <%= render "shared/error_message", attribute: :duration, object: talk %>
      <p>You'll have time for ~ <span data-duration-target="showSelectedDuration">6</span> topics</p>
    </div>

</div>

</div>
<div class="mt-8 flex flex-row justify-between">
  <%= link_to root_path do %>
    <div class="hvr-grow active:bg-blurple-gray cursor-pointer my-shadow-lg bg-white text-lg font-bold h-14 w-14">
      <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Chevron_small_left" x="0px" y="0px" viewBox="0 0 20 20" enable-background="new 0 0 20 20" xml:space="preserve">
        <path fill="#000" d="M12.141,13.418c0.268,0.271,0.268,0.709,0,0.978c-0.268,0.27-0.701,0.272-0.969,0l-3.83-3.908  c-0.268-0.27-0.268-0.707,0-0.979l3.83-3.908c0.267-0.27,0.701-0.27,0.969,0c0.268,0.271,0.268,0.709,0,0.978L9,10L12.141,13.418z" />
      </svg>
    </div>
  <% end %>
  <%= form.submit submit_text, method: method, class: "h-14 uppercase hvr-grow px-8 my-shadow-lg text-lg font-bold bg-blue text-white active:bg-blue-darker cursor-pointer" %>
</div>
<% end %>

app/views/talks/_intro_facilitator.html.erb
<div class="bg-white my-8 p-8 my-shadow">
  <div class="flex flex-row gap-8 overflow-hidden justify-center">
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
  </div>
  <div class="flex flex-col items-center py-16 font-light leading-loose">
    <%= render partial: "talks/participants", locals: { talk: talk, participants: participants }  %>
  </div>
</div>

<div class="flex flex-row justify-between">

  <%= link_to edit_talk_path(talk), data: { turbo: false }, class: "flex items-center w-1/6 px-8 bg-white text-blue-dark font-medium my-shadow transition duration-200 ease-in-out transform hover:bg-gray-200 active:bg-gray-400" do %>
    <div class="flex flex-row w-full justify-between uppercase font-bold">
      <span class="material-icons">arrow_back_ios</span>
      <p>Edit</p>
      <p></p>
    </div>
  <% end %>

  <div class="flex flex-row justify-between gap-8">
    <div data-controller="clipboard" data-action="click->clipboard#copy click->clipboard#copiedFromButton" class="transition duration-200 ease-in-out transform hover:bg-gray-200 active:bg-gray-400 md:py-4 lg:py-0 bg-white border-4 border-solid border-blue-dark tooltip cursor-pointer">
      <p data-clipboard-target="copiedButtonElement" class="px-8 text-blue-dark md:text-6xl lg:text-xl font-medium py-2 text-center">Invite link</p>
    </div>

    <%= form_with model: talk, method: :patch, data: { turbo: false }, class: "flex flex-row" do |form| %>
      <%= form.hidden_field :state, :value => 2 %>
      <%= button_tag "Start session", class: "transition duration-200 ease-in-out transform hover:bg-blue-darker active:bg-blue-dark bg-blue cursor-pointer text-white w-full" do %>
            <p class="text-xl font-medium py-2 text-center uppercase px-16">Start session</p>
      <% end %>
    <% end %>
  </div>

</div>

app/views/talks/_intro_participant.html.erb
<div class="bg-white my-8 p-8 my-shadow">
  <div class="flex flex-row gap-8 overflow-hidden justify-center">
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
    <span class="material-icons text-beige">circle</span>
  </div>
  <div class="flex flex-col items-center py-16 font-light italic leading-loose uppercase">
    <p>Waiting for <%= talk.facilitator.name %> to start the session</p>
  </div>
</div>

app/views/talks/_partial_show.html.erb
<div data-controller="facilitator" id=<%= dom_id(talk) %>>
  <div class="flex flex-row justify-between gap-12 my-8">
    <div class="w-full" >
        <% case talk.state %>
          <% when 1 %>
          <%= render "talks/title", talk: talk, text: talk.theme %>
          <% when 2 %>
          <%= render "talks/title", talk: talk, text: "Come up with some topics for the talk" %>
          <% when 3 %>
          <%= render "talks/title", talk: talk, text: "Vote on the most important topics" %>
          <% when 4 %>
          <%= render "talks/title", talk: talk, text: "Here's a topic to discuss" %>
          <% when  5 %>
          <%= render "talks/title", talk: talk, text: "Here's a recap of what you did" %>
        <% end %>
      <div class="mt-4">
      <% case talk.state %>
        <% when 1 %>
        <div data-facilitator-target="Facilitator" class="hidden">
          <%= render "talks/intro_facilitator", talk: talk, participants: participants %>
        </div>
        <div data-facilitator-target="Participant" class="hidden">
          <%= render "talks/intro_participant", talk: talk %>
        </div>
        <% when 2 %>
          <%= render "topics/new", talk: talk %>
        <% when 3 %>  
          <%#= render "votes/show" %>
        <% when 5 %>  
          <%= render "talks/recap", talk: talk %>
      <% end %>
      </div>
      <%= render "talks/topics", talk: talk, topics: topics %>
    </div>

    <div>
      <%= render "talks/talk", talk: talk %>
    </div>
  </div>
</div>

app/views/talks/_participants.html.erb
<div id=<%= dom_id(talk, :participants) %> class="my-2 gap-2 flex-wrap flex items-start w-full">

<%= (render partial: "visitors/participant", collection: participants, locals: { talk: talk }) || content_tag(:p, "No one is here yet! Invite some people", class: "text-center w-full") %>

</div>

app/views/talks/_recap.html.erb
<h2 class="mt-4 bg-green text-white text-2xl font-bold p-4 px-4 uppercase">Here are the topics you talked about</h2>

app/views/talks/_talk.html.erb
<% if talk.state > 1 %>
  <div id="<%= dom_id talk %>" class="text-white flex flex-col items-center w-full lg:w-64 bg-white lg:p-6">
      <div class="flex flex-col text-white font-bold w-full">
        <div class="bg-blue flex items-end justify-around pt-16 pb-4">
          <p class="uppercase italic text-lg w-1/2">Topics</p>
          <p class="text-6xl leading-none"><span id="topics_count"><%= talk.topics.count %></span></p>
        </div>
        <div class="p-4 text-center text-sm bg-blue opacity-50">
          <% if talk.state < 3 %>
            <p>Keep them coming!</p>
          <% end %>
          <% if talk.state == 3 %>
            <p>Time to vote!</p>
          <% end %>
          <% if talk.state == 4 %>
            <p>You're doing great!</p>
          <% end %>
          <% if talk.state == 5 %>
            <p>Well done!</p>
          <% end %>
        </div>
      </div>

    <div data-facilitator-target="Facilitator" class="bg-blue mt-2 w-full hidden">
      <% case talk.state %>
        <% when 2 %>
          <div class="flex flex-row justify-between bg-white w-full">
            <%= render "shared/nav_form", talk: talk, state: 1, text: "Back", class: "font-bold uppercase" %>
            <%= render "shared/nav_form", talk: talk, state: 3, text: "next", class: "font-bold uppercase" %>
          </div>
        <% when 3 %>
          <div class="flex flex-row  justify-between bg-white w-full">
            <%= render "shared/nav_form", talk: talk, state: 2, text: "Back", class: "font-bold uppercase" %>
            <%= render "shared/nav_form", talk: talk, state: 4, text: "next", class: "font-bold uppercase" %>
          </div>
        <% when 4 %>
          <div class="flex flex-row justify-between bg-white w-full">
            <%= render "shared/nav_form", talk: talk, state: 3, text: "Back", class: "font-bold uppercase" %>
            <%= render "shared/nav_form", talk: talk, state: 5, text: "next", class: "font-bold uppercase" %>
          </div>
        <% when 5 %>
          <div class="flex flex-col bg-white gap-8">
            <%= render "shared/nav_form", talk: talk, state: 4, text: "Back", class: "font-bold uppercase" %>
            <%= link_to "Create new talk", new_talk_path, data: { turbo: false }, class: "transition duration-200 ease-in-out transform hover:bg-green-dark active:bg-green-darker bg-green uppercase text-lg font-medium py-2 text-center bg-blue" %>
          </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/talks/_title.html.erb
<h1 class="<%= talk.state == 3 ? "bg-red" : "bg-black" %> my-shadow w-<%= talk.state == 1 ? "1/2" : "full" %> text-white text-4xl font-bold p-4 uppercase"><%= text %></h1>

app/views/talks/_topics.html.erb
<div id="topics" class="my-2 gap-2 flex-col flex bg-white my-shadow-lg">
<%= render partial: "topics/topic", collection: topics, locals: { talk: talk, topics: topics  } %>
</div>

app/views/talks/edit.html.erb
<%= render "form", talk: @talk, visitor: @visitor, submit_text: "Update talk", method: :patch %>

app/views/talks/index.html.erb
<div class="bg-blue flex-col flex p-12 h-full mb-4 mt-4">
<a href="/" class="lg:-ml-16 lg:-mt-0 z-50 -ml-4 mt-4 italic bg-black w-12 h-12 lg:w-16 lg:h-16 text-yellow-50 text-3xl lg:text-5xl flex font-bold items-center justify-center">
<span>T</span>
</a>
  <div class="-mt-12 lg:-mt-16">
    <div class="frontpage-bg flex flex-col mx-8 h-full">
      <div class="bg-transparent lg:w-5/12 w-full flex flex-col mt-56">
        <div class="py-8 ml-8 pl-8 gap-4 flex flex-col mb-8 bg-blue">
          <h1 class="uppercase leading-tight text-5xl font-bold text-yellow-50 bg-blue">
            <p>Talk about</p>
            <p>what matters</p>
          </h1>
          <%= link_to "Create talk", new_talk_path , class: "lg:w-2/3 w-full uppercase text-center text-lg py-4 bg-yellow-50 focus:outline-none active:bg-gray-200 text-blue font-bold", data: { turbo: false } %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/talks/new.html.erb
<%= render "form", talk: @talk, visitor: @visitor, submit_text: "Create talk", method: :post %>

app/views/talks/show.html.erb
<%= turbo_stream_from "topics_stream" %>
<%= turbo_stream_from "participants_stream" %>
<%= turbo_stream_from "topic_count_stream" %>
<%= turbo_stream_from "state_stream" %>
<%= turbo_stream_from "vote_count_stream" %>

<%= render "shared/dev_nav" if Rails.env.development? %>
<div id=<%= dom_id(@talk) %>>
  <%= render "talks/partial_show", talk: @talk, topics: @topics, participants: @participants %>
</div>